[[actions]]
name = "play"
path = "@PKG_ITCH_PLAY_PATH@"

[[actions]]
name = "Open Maps Folder"
path = "@PKG_ITCH_RES_PATH@/assets/maps/"

[[actions]]
name = "Open Online Maps Guide"
path = "https://github.com/esotericpig/EkoScape/blob/main/assets/maps/README.md"

[[actions]]
name = "Open Offline Maps Guide"
path = "@PKG_ITCH_RES_PATH@/assets/maps/README.html"
