[[actions]]
name = "Open Maps Folder"
path = "assets/maps/"
platform = "linux"

[[actions]]
name = "Open Maps Folder"
path = "EkoScape.app/Contents/Resources/assets/maps/"
platform = "osx"

[[actions]]
name = "Open Maps Folder"
path = "assets/maps/"
platform = "windows"

[[actions]]
name = "Maps Guide"
path = "https://github.com/esotericpig/EkoScape/blob/main/assets/maps/README.md"
