name: macOS uni

on:
  workflow_dispatch:
#  push:
#    branches: [ 'test-gh-ci' ]

env:
  VCPKG_ROOT: "${{ github.workspace }}/vcpkg"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Install sys deps
        run: |
          brew install glew

      - name: Check out repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install CMake & Ninja
        uses: lukka/get-cmake@latest

      - name: Install vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: "${{ env.VCPKG_ROOT }}"
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Configure build arm64
        run: >
          cmake --preset default
          -DBUILD_SHARED_LIBS=OFF
          -DCMAKE_OSX_ARCHITECTURES=arm64
          -DVCPKG_OSX_ARCHITECTURES=arm64
          -DVCPKG_TARGET_TRIPLET="arm64-osx"
          -DVCPKG_CRT_LINKAGE=static
          -DVCPKG_LIBRARY_LINKAGE=static
          -DVCPKG_BUILD_TYPE=release
          -DPKG_SUFFIX="-uni"
          -DPKG_MACOS_BUILD_UNI_DIR=ON
      - name: Build arm64
        run: cmake --build --preset no-jobs --config Release
      - name: Move bin arm64
        run: |
          set -x
          mkdir -pv build_uni_temp
          mv -v bin/Release/EkoScape build_uni_temp/EkoScape-arm64
          set +x
      - name: Clean arm64
        run: |
          set -x
          rm -rf bin build
          set +x

      - name: Configure build x86_64
        run: >
          cmake --preset default
          -DBUILD_SHARED_LIBS=OFF
          -DCMAKE_OSX_ARCHITECTURES=x86_64
          -DVCPKG_OSX_ARCHITECTURES=x86_64
          -DVCPKG_TARGET_TRIPLET="x64-osx"
          -DVCPKG_CRT_LINKAGE=static
          -DVCPKG_LIBRARY_LINKAGE=static
          -DVCPKG_BUILD_TYPE=release
          -DPKG_SUFFIX="-uni"
          -DPKG_MACOS_BUILD_UNI_DIR=ON
      - name: Build x86_64
        run: cmake --build --preset no-jobs --config Release
      - name: Move bin x86_64
        run: |
          set -x
          mkdir -pv build_uni_temp
          mv -v bin/Release/EkoScape build_uni_temp/EkoScape-x86_64
          set +x
      # Do NOT clean.

      # vcpkg doesn't currently support universal macOS binaries, so making manually.
      # See `CMakeLists.txt` for `build_uni` config.
      - name: Build uni
        run: |
          set -x
          mkdir -pv build_uni
          lipo -create build_uni_temp/EkoScape* -output build_uni/EkoScape
          lipo -info build_uni/EkoScape
          set +x

      - name: Package up
        run: cmake --build --preset no-jobs --config Release --target package

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          path: |
            build/*.zip
            build/*.sha256
          if-no-files-found: error
          compression-level: 0
          overwrite: true
          include-hidden-files: false
